"""Offline foundation for topic-aware 7–8 scene dual-tier production."""

from .execution import (
    build_fixture_preview_run,
    build_production_run_plan,
    deterministic_scene_seed,
)
from .execution_models import (
    ApprovedReference,
    ExecutionMode,
    ProductionRunPlan,
    ReferenceCatalog,
    ReferenceDecision,
    ReferenceDecisionStatus,
    SceneExecutionPlan,
)
from .manifest import build_initial_manifest, refresh_manifest_readiness
from .models import (
    AcceptancePriority,
    CandidateArtifact,
    DualTierPolicy,
    GenerationTier,
    PlannerMode,
    ProductionManifest,
    ProductionScene,
    ProductionSceneBrief,
    ProductionSceneStatus,
    ReadinessResult,
    SceneComplexity,
    SceneType,
    SemanticBeat,
    StoryPlan,
)
from .planner import (
    DeterministicTopicPlanner,
    TopicFidelityEvaluator,
    TopicStoryPlanner,
    build_scene_briefs,
    validate_topic_fidelity,
)
from .readiness import evaluate_render_readiness
from .reference_planning import (
    APPROVED_REFERENCE_DEFINITIONS,
    ApprovedReferenceValidationError,
    load_reference_catalog,
    resolve_references,
)
from .runtime import (
    authorize_draft_acceptance,
    block_scene,
    evaluate_execution_readiness,
    initialize_execution_state,
    plan_resume,
    promote_scene_to_acceptance,
    record_generation_attempt,
    record_human_qc,
    record_qc,
    register_accepted_candidate,
    summarize_call_budget,
)
from .runtime_models import (
    AcceptedCandidateRecord,
    CallBudgetSummary,
    ExecutionEvent,
    ExecutionRunState,
    FailureReason,
    GenerationAttempt,
    PromotionReason,
    QCCheckOutcome,
    QCChecks,
    QCDecision,
    QCRecord,
    QCEvaluator,
    ResumeAction,
    ResumePlan,
    ReviewSource,
    TechnicalStatus,
)
from .simulation import simulate_eight_scene_execution
from .visual_adapter import adapt_scene_brief, required_reference_roles

__all__ = [
    "AcceptancePriority",
    "AcceptedCandidateRecord",
    "ApprovedReference",
    "ApprovedReferenceValidationError",
    "APPROVED_REFERENCE_DEFINITIONS",
    "CandidateArtifact",
    "CallBudgetSummary",
    "DeterministicTopicPlanner",
    "DualTierPolicy",
    "ExecutionMode",
    "ExecutionEvent",
    "ExecutionRunState",
    "FailureReason",
    "GenerationTier",
    "GenerationAttempt",
    "PlannerMode",
    "ProductionManifest",
    "ProductionRunPlan",
    "ProductionScene",
    "ProductionSceneBrief",
    "ProductionSceneStatus",
    "PromotionReason",
    "QCCheckOutcome",
    "QCChecks",
    "QCDecision",
    "QCEvaluator",
    "QCRecord",
    "ReadinessResult",
    "ReferenceCatalog",
    "ReferenceDecision",
    "ReferenceDecisionStatus",
    "ResumeAction",
    "ResumePlan",
    "ReviewSource",
    "SceneComplexity",
    "SceneExecutionPlan",
    "SceneType",
    "SemanticBeat",
    "StoryPlan",
    "TechnicalStatus",
    "TopicFidelityEvaluator",
    "TopicStoryPlanner",
    "adapt_scene_brief",
    "authorize_draft_acceptance",
    "block_scene",
    "build_fixture_preview_run",
    "build_initial_manifest",
    "build_production_run_plan",
    "build_scene_briefs",
    "deterministic_scene_seed",
    "evaluate_render_readiness",
    "evaluate_execution_readiness",
    "initialize_execution_state",
    "load_reference_catalog",
    "refresh_manifest_readiness",
    "plan_resume",
    "promote_scene_to_acceptance",
    "record_generation_attempt",
    "record_human_qc",
    "record_qc",
    "register_accepted_candidate",
    "required_reference_roles",
    "resolve_references",
    "simulate_eight_scene_execution",
    "summarize_call_budget",
    "validate_topic_fidelity",
]
